### ISSUE TITLE
Submodule init?

### ISSUE THREAD

**Issue by robertjd** [stormpath/stormpath-sphinx-theme#1]
Hey yo, 

After doing:

```
git submodule add https://github.com/stormpath/stormpath-sphinx-theme.git docs/_themes/stormpath
```

I had to go into the "stormpath" folder, and then do this in order to pull down the files inside the module:

```
git submodule init
git submodule update
```

Is this normal?  If so I'll add to README.  Thanks!

**Comment by omgitstom** [comment]
That is normal for the submodule flow in git.  One of the biggest issue with them in all honesty

**Comment by rdegges** [comment]
Fixed =)

I didn't include this originally, because my idea was to have a build system to auto-build all the docs, but since that's a bit far out I updated the readme =)

**Comment by robertjd** [comment]
Cool thanks!  Would you be down for putting this submodule setup as an npm post-install task for express-stormpath?  I realized today that we don;t offer much help for people who want to make PRs for the docs.

Regarding the development process around docs, in the Angular libray I setup a cool Grunt task which will watch the docs and serve them in a livereload server - so they change as you edit them :) might be night to add that to express-stormpath, too!

**Comment by rdegges** [comment]
Hmm, I don't think so. The reason is that express-stormpath doesn't include the docs directory at all -- so it will cause other issues even if the git submodule is added successfully. If you look at the npmignore, it contains the docs folder.

I think the right way to do this, for the record, is to use github webhooks to hit our own internal docs server, after which point we clone the repo, init all submodules, then run 'make html' from the docs directory.

This is what https://readthedocs.org/ does.

**Comment by robertjd** [comment]
I think you're talking about the process of building and deploying docs to our public site?  I'm talking about workflows that a developer can use locally to make documentation changes (and see those changes) before making a PR into the library with said changes.

**Comment by robertjd** [comment]
In other words: I want to facilitate what we're seeing on the Angular library (with documentation PRs) in the stormpath-express library, too

**Comment by rdegges** [comment]
Oh -- how would that work? Is there a way to do that with npm so it'll only run a task if the package is installed locally as opposed to via npm directly?

**Comment by robertjd** [comment]
Not sure what you mean by local vs. direct, but now I'm thinking it;s silly to always install this template (which is what would happen as an npm post-install task)

If we bring Grunt into stormpath-express, it would be pretty trivial to script all this with a Grunt task.

**Comment by rdegges** [comment]
Yah -- I think it's probably better to have some sort of Grunt / Gulp workflow for local development type tasks. It's also sort of hard to do this thing by default, I think, since Sphinx itself requires a working python installation and other dependencies.

I think it's generally best to have docs available in the contributing section somewhere to describe HOW to build / work on the docs -- but to also have an automated build process for docs in our own internal stuff in the long run.
